version: "3.8"

services:
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    networks:
      - react-network
  backend:
    build: ./backend
    depends_on:
      - mongodb
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ./backend:/app
    networks:
      - react-network
  frontend:
    depends_on:
      - backend
    build: ./frontend
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./frontend:/app
    networks:
      - react-network
  frontend-with-redux:
    depends_on:
      - backend
    build: ./frontend-with-redux
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./frontend-with-redux:/app
    networks:
      - react-network

networks:
  react-network:
    driver: bridge
